owner: CORDTOWN
repo: upptime

sites:
  - name: Movie-RSS
    url: https://movie-rss.cord.town/
  - name: Tech-RSS
    url: https://tech-rss.cord.town/  
  - name: Journalism-RSS
    url: $SECRET_SITE

status-website:
  cname: status.cord.town
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for CORD TOWN"
  introMessage: 코드타운에서 운영하는 서비스를 모니터링 합니다.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://discord.cord.town
