owner: CORDTOWN
repo: upptime

sites:
  - name: LOONA-RSS
    url: https://loona-rss.cord.town/
  - name: TICKET-RSS
    url: https://ticket-rss.cord.town/
  - name: MUSIC-RSS
    url: https://music-rss.cord.town/
  - name: MOVIE-RSS
    url: https://movie-rss.cord.town/
  - name: TECH-RSS
    url: https://tech-rss.cord.town/  
  - name: JOURNALISM-RSS
    url: https://journalism-rss.cord.town/

status-website:
  cname: status.cord.town
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for CORD TOWN"
  introMessage: 코드타운에서 운영하는 서비스를 모니터링 합니다.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://discord.cord.town
